[package]
name = "merveille"
version = "0.0.0"
authors = ["Aaron Weiss <awe@pdgn.co>"]

[dependencies]
diesel = { version = "1.1", features = ["sqlite"] }
dotenv = "0.9"
env_logger = "0.5"
failure = "0.1"
log = "0.4"
irc = { git = "https://github.com/aatxe/irc", branch = "develop", features = ["ctcp", "toml"] }
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
